### PR TITLE
Big refactor/redesign of the homepage

### PR DESCRIPTION
**Pull request by wesoudshoorn**
# Hey Euruko team :)
I noticed that @tombruijn was struggling a bit with improving the homepage. I really appreciate the volunteer work you all are doing for the community, so I went down the rabbit hole to improve your homepage. 

My main goal was to improve the visual design of some elements. The color palette, readability and design had some areas from improvement. After diving in, I restructured _a lot_ of the front-end, cutting it up into separate CSS files and introducing some global styles.

I understand that this makes the PR a bit hard to review on the code level, so please look at the results of the changes mostly, and let me know if I introduced any bugs. I'd be happy to help out a little towards the conference 💯 

# Screenshot
screencapture-localhost-5000-2019-03-19-11_07_23

# Full list of changes
- Cleaned up CSS
- Remove much specific scoping in CSS
- Moved CSS to smaller files
- Improved typography and readability
- Inline images instead of css bg’s for logos
- Improved readability of the program
- Accessibility improved
  - Improved color contrast
  - Better heading structures

### CODE REVIEW

**Comment by tombruijn** [comment]
Hi @wesoudshoorn!

Thanks for the PR! 🚀 

I do see that the sponsoring page broke a bit during this refactor. Can you have a look at that?

You can reach it at http://localhost:5000/sponsoring/

image

**Comment by wesoudshoorn** [comment]
Will do!

**Comment by tombruijn** [comment]
Thanks! I'll fix up a small things directly on master

**Comment by raytalks** [comment]
@wesoudshoorn Thank you so much for helping us out here!

**Pull request merged**
